global using Microsoft.EntityFrameworkCore;
global using MVC_CRUD.Data;
global using System.ComponentModel.DataAnnotations;
global using MVC_CRUD.ViewModels;
global using MVC_CRUD.Models;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using MVC_CRUD.Services;
global using Microsoft.AspNetCore.Mvc;
global using MVC_CRUD.Settings;
